- name: 必要パッケージのインストール
  apt: name={{ item }}
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - imagemagick
    - libapr1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - libmagick++-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - openssl
    - zlib1g
    - zlib1g-dev
