- name: 必要パッケージのインストール
  apt: pkg={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - imagemagick
    - imagemagick-dbg
    - libapr1-dev
    - libcurl4-openssl-dev
    - libmagick++-dev
    - libreadline-dev
    - libreadline6
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - openssl
    - zlib1g
    - zlib1g-dev

