# Common prereqs (e.g. build tools, libs)
- include: common-prereqs.yml

# rbenv setup
- include: rbenv-setup.yml
  become_user: "{{ rbenv.user }}"

# Common ruby environment tasks (e.g. adding a .gemrc, ...)
- include: common-post.yml
  become_user: "{{ rbenv.user }}"
