
- name: rbenvをgit clone
  git: repo=https://github.com/sstephenson/rbenv.git dest=~{{ rbenv.user }}/.rbenv accept_hostkey=yes

- name: bash_profile配置
  copy: src=bash_profile dest=~{{ rbenv.user }}/.bash_profile mode=755 owner={{ rbenv.user }}

- name: プラグインディレクトリ作成
  file: path=~{{ rbenv.user }}/.rbenv/plugins/ owner={{ rbenv.user }} group={{ rbenv.user }} mode=0755 state=directory

- name: ruby-buildインストール
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~{{ rbenv.user }}/.rbenv/plugins/ruby-build

- name: rbenvにインストールされてるバージョンチェック
  shell: cd; bash -lc "rbenv versions | grep -q {{ rbenv.install_ruby_version }}"
  register: result
  ignore_errors: true

- name: Installs ruby
  shell: cd; bash -lc "CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ rbenv.install_ruby_version }}"
  when: result.rc != 0

- name: Sets global ruby version
  shell: cd; bash -lc "rbenv global {{ rbenv.default_ruby_version }}"

- name: rbenv rehash
  shell: cd; bash -lc "rbenv rehash"

- name: Bundlerインストール
  shell: cd; bash -lc "gem install bundler"





